purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.7663802
  lightness: 0.5
  brandColors:
    - '#ffffff'
    - '#565656'
    - '#b7bb5c'
    - '#050706'
    - '#909090'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Ben-Daly
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.50828
layout_spectrum: 1
