name: Ben-Daly
favicon: null
layout_spectrum: 0.2899113087914884
typography_spectrum: 0.0002806412521749735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0318464282900095
  lightness: 0.1671129036694765
  saturation: 0.8037144641857594
  rhythmicContrast: 0.9541773933451623
purpose: []
